// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class MachineLog
    {
        public MachineLog()
        {
            MachineLogDetails = new HashSet<MachineLogDetail>();
        }

        public int PrinterId { get; set; }
        public string JobId { get; set; }
        public int ImportId { get; set; }
        public int? TotalFile { get; set; }
        public string Sender { get; set; }
        public DateTime? DateStart { get; set; }
        public string RawData { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual ImportFile Import { get; set; }
        public virtual MasterType Printer { get; set; }
        public virtual ICollection<MachineLogDetail> MachineLogDetails { get; set; }
    }
}