// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class MachineLogDetail
    {
        public int PrinterId { get; set; }
        public string JobId { get; set; }
        public int FileId { get; set; }
        public int ImportId { get; set; }
        public string JobName { get; set; }
        public string JobType { get; set; }
        public string FullPath { get; set; }
        public DateTime? DateEnd { get; set; }
        public int? TotalPage { get; set; }
        public string RawData { get; set; }
        public DateTime DateCreated { get; set; }
        public int? ImportIdModified { get; set; }
        public DateTime? DateModified { get; set; }

        public virtual ImportFile Import { get; set; }
        public virtual ImportFile ImportIdModifiedNavigation { get; set; }
        public virtual MachineLog MachineLog { get; set; }
    }
}