// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class MasterType
    {
        public MasterType()
        {
            ImportFiles = new HashSet<ImportFile>();
            MachineLogs = new HashSet<MachineLog>();
        }

        public int TypeId { get; set; }
        public int? ParentTypeId { get; set; }
        public string TypeName { get; set; }
        public int? RefNo { get; set; }
        public int? CycleTime { get; set; }

        public virtual ICollection<ImportFile> ImportFiles { get; set; }
        public virtual ICollection<MachineLog> MachineLogs { get; set; }
    }
}