// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class MasterType
    {
        public int TypeId { get; set; }
        public int? ParentTypeId { get; set; }
        public string TypeName { get; set; }
        public int? CycleTime { get; set; }
    }
}