// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class PrinterLogDetail
    {
        public int PrinterId { get; set; }
        public string JobId { get; set; }
        public int CycleTime { get; set; }
        public int FileId { get; set; }
        public string JobType { get; set; }
        public string FullPath { get; set; }
        public string JobName { get; set; }
        public int? Filesize { get; set; }
        public int? Copies { get; set; }
        public string Formdef { get; set; }
        public string Pagedef { get; set; }
        public string UserExplorer { get; set; }
        public int? StatusExplorer { get; set; }
        public string Printer { get; set; }
        public int? Jobqueue { get; set; }
        public string Range { get; set; }
        public string Form { get; set; }
        public bool? Simplex { get; set; }
        public bool? Duplex { get; set; }
        public int? TotalPage { get; set; }
        public int? OriginalPages { get; set; }
        public int? FrontPages { get; set; }
        public int? BackPages { get; set; }
        public int? TotalSheets { get; set; }
        public int? InformationPages { get; set; }
        public int? InformationSheets { get; set; }
        public int? TotalOffsets { get; set; }
        public int? Feet { get; set; }
        public int? Nup { get; set; }
        public int? WidthPage { get; set; }
        public int? LengthPage { get; set; }
        public DateTime? DateSubmission { get; set; }
        public DateTime? DateStartQueue { get; set; }
        public DateTime? DateEndQueue { get; set; }
        public DateTime? DateStart { get; set; }
        public DateTime? DateEnd { get; set; }
        public string RawData { get; set; }
        public DateTime DateCreated { get; set; }
        public int ImportId { get; set; }
        public int? ImportIdModified { get; set; }
        public DateTime? DateModified { get; set; }
        public int LastRecordType { get; set; }
    }
}