// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class PrinterLog
    {
        public int PrinterId { get; set; }
        public string JobId { get; set; }
        public int CycleTime { get; set; }
        public string Client { get; set; }
        public string Sender { get; set; }
        public string Printer { get; set; }
        public int? Jobqueue { get; set; }
        public int? Resolution { get; set; }
        public bool? Proofprint { get; set; }
        public bool? Storeprint { get; set; }
        public string CustAcc { get; set; }
        public string ReferenceId { get; set; }
        public string Form { get; set; }
        public string TicketName { get; set; }
        public string JobName { get; set; }
        public string OrderId { get; set; }
        public string Range { get; set; }
        public string ColorIds { get; set; }
        public bool? TrackingEnabled { get; set; }
        public int? TotalFile { get; set; }
        public string UserExplorer { get; set; }
        public int? StatusExplorer { get; set; }
        public string JobType { get; set; }
        public bool? Simplex { get; set; }
        public bool? Duplex { get; set; }
        public int? TotalPage { get; set; }
        public int? OriginalPages { get; set; }
        public int? FrontPages { get; set; }
        public int? BackPages { get; set; }
        public int? TotalSheets { get; set; }
        public int? InformationPages { get; set; }
        public int? InformationSheets { get; set; }
        public int? TotalOffsets { get; set; }
        public int? Feet { get; set; }
        public int? Nup { get; set; }
        public int? WidthPage { get; set; }
        public int? LengthPage { get; set; }
        public DateTime? DateSubmission { get; set; }
        public DateTime? DateExplorer { get; set; }
        public DateTime? DateStartQueue { get; set; }
        public DateTime? DateEndQueue { get; set; }
        public DateTime? DateStart { get; set; }
        public DateTime? DateEnd { get; set; }
        public string RawData { get; set; }
        public DateTime DateCreated { get; set; }
        public int ImportId { get; set; }
        public int? ImportIdModified { get; set; }
        public DateTime? DateModified { get; set; }
        public int LastRecordType { get; set; }
    }
}