// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class RecordType
    {
        public int RecordType1 { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsJob { get; set; }
        public bool? IsSubJob { get; set; }
    }
}