// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PrintLog.DAL.Models
{
    public partial class VwImportFile
    {
        public int ImportId { get; set; }
        public string FileName { get; set; }
        public int CountJob { get; set; }
        public int CountLine { get; set; }
        public bool IsSuccess { get; set; }
        public int PrinterId { get; set; }
        public DateTime DateCreated { get; set; }
        public string ErrorMessage { get; set; }
        public string PrinterName { get; set; }
    }
}