// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PrintLog.DAL.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PrintLog.DAL.Models;

namespace PrintLog.DAL.Data
{
    public partial class PrintlogDbContext : DbContext
    {
        public PrintlogDbContext()
        {
        }

        public PrintlogDbContext(DbContextOptions<PrintlogDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ImportFile> ImportFiles { get; set; }
        public virtual DbSet<MasterType> MasterTypes { get; set; }
        public virtual DbSet<PrinterLog> PrinterLogs { get; set; }
        public virtual DbSet<PrinterLogDetail> PrinterLogDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ImportFile>(entity =>
            {
                entity.HasKey(e => e.ImportId)
                    .HasName("PK_Imports");

                entity.Property(e => e.DateCreated)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.FileName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<MasterType>(entity =>
            {
                entity.HasKey(e => e.TypeId);

                entity.Property(e => e.TypeId).ValueGeneratedNever();

                entity.Property(e => e.TypeName)
                    .IsRequired()
                    .HasMaxLength(256);
            });

            modelBuilder.Entity<PrinterLog>(entity =>
            {
                entity.HasKey(e => new { e.PrinterId, e.JobId, e.CycleTime });

                entity.Property(e => e.JobId).HasMaxLength(128);

                entity.Property(e => e.Client).HasMaxLength(256);

                entity.Property(e => e.ColorIds).HasMaxLength(256);

                entity.Property(e => e.CustAcc).HasMaxLength(256);

                entity.Property(e => e.DateCreated).HasColumnType("datetime");

                entity.Property(e => e.DateEnd).HasColumnType("datetime");

                entity.Property(e => e.DateEndQueue).HasColumnType("datetime");

                entity.Property(e => e.DateExplorer).HasColumnType("datetime");

                entity.Property(e => e.DateModified).HasColumnType("datetime");

                entity.Property(e => e.DateStart).HasColumnType("datetime");

                entity.Property(e => e.DateStartQueue).HasColumnType("datetime");

                entity.Property(e => e.DateSubmission).HasColumnType("datetime");

                entity.Property(e => e.Form).HasMaxLength(256);

                entity.Property(e => e.JobName).HasMaxLength(256);

                entity.Property(e => e.JobType).HasMaxLength(256);

                entity.Property(e => e.OrderId).HasMaxLength(256);

                entity.Property(e => e.Printer).HasMaxLength(256);

                entity.Property(e => e.Range).HasMaxLength(256);

                entity.Property(e => e.ReferenceId).HasMaxLength(256);

                entity.Property(e => e.Sender).HasMaxLength(256);

                entity.Property(e => e.TicketName).HasMaxLength(256);

                entity.Property(e => e.UserExplorer).HasMaxLength(256);
            });

            modelBuilder.Entity<PrinterLogDetail>(entity =>
            {
                entity.HasKey(e => new { e.PrinterId, e.JobId, e.CycleTime, e.FileId });

                entity.Property(e => e.JobId).HasMaxLength(256);

                entity.Property(e => e.DateCreated).HasColumnType("datetime");

                entity.Property(e => e.DateEnd).HasColumnType("datetime");

                entity.Property(e => e.DateEndQueue).HasColumnType("datetime");

                entity.Property(e => e.DateModified).HasColumnType("datetime");

                entity.Property(e => e.DateStart).HasColumnType("datetime");

                entity.Property(e => e.DateStartQueue).HasColumnType("datetime");

                entity.Property(e => e.DateSubmission).HasColumnType("datetime");

                entity.Property(e => e.Form).HasMaxLength(256);

                entity.Property(e => e.Formdef).HasMaxLength(256);

                entity.Property(e => e.JobName).HasMaxLength(256);

                entity.Property(e => e.JobType).HasMaxLength(256);

                entity.Property(e => e.Pagedef).HasMaxLength(256);

                entity.Property(e => e.Printer).HasMaxLength(256);

                entity.Property(e => e.Range).HasMaxLength(256);

                entity.Property(e => e.UserExplorer).HasMaxLength(256);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}